resources:
- manager.yaml
- webhook_service.yaml
- configmap.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- envs:
  - manager.env
  files:
  - controller_manager_config.yaml
  name: manager-config

patchesStrategicMerge:
- deployment-env-patch.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/ocs-dev/odf-operator
  newTag: latest
